name: Build with CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up MinGW
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -yq --no-install-recommends mingw-w64

      - name: Configure
        run: |
          cmake \
            -DCMAKE_TOOLCHAIN_FILE=cmake/mingw-w64-x86_64.cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DSTATIC_ZLIB=ON \
            -B build -S .

      - name: Build
        run: |
          cmake --build build \
            --config Release \
            --target pmlxzj_unlocker

      - uses: actions/upload-artifact@v4
        with:
          name: pmlxzj_unlocker
          path: build/*.exe
